name: remindee_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.4.0
  awesome_notifications: ^0.9.3+1
  flutter_timetable: ^1.1.6
  syncfusion_flutter_calendar: ^26.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
